import type { Session } from "./types"

/* ══════════════════════════════════════════════════════════════
   SESSION DATA — each is a "moment" in the day.
   ══════════════════════════════════════════════════════════════ */

export const sessions: Session[] = [
  /* 0 ── morning boot */
  {
    time: "06:42 AM", label: "Morning Boot", icon: "☕",
    lines: [
      { t: "cmd", s: "cd ~/agents && source .venv/bin/activate" },
      { t: "out", s: "(venv) ✓ Python 3.12.4 — torch 2.3.1+cu121 — CUDA 12.1", d: 60 },
      { t: "cmd", s: "git pull origin main --rebase" },
      { t: "out", s: "Fast-forward | 14 files changed, 847 insertions(+), 203 deletions(-)", d: 80 },
      { t: "cmd", s: "pytest tests/ -x -q --tb=line" },
      { t: "out", s: "142 passed in 3.1s", d: 120, c: "text-emerald-400" },
      { t: "cmd", s: "docker compose up -d redis postgres qdrant" },
      { t: "out", s: "✔ Container redis         Started   0.3s", d: 50 },
      { t: "out", s: "✔ Container postgres       Started   0.4s" },
      { t: "out", s: "✔ Container qdrant         Started   0.6s" },
      { t: "out", s: "All services healthy ✓", c: "text-emerald-400" },
    ],
  },
  /* 1 ── code-review agent */
  {
    time: "07:15 AM", label: "Code-Review Agent", icon: "🤖",
    lines: [
      { t: "hdr", s: "# agents/code_review.py" },
      { t: "code", s: "class CodeReviewAgent(BaseAgent):" },
      { t: "code", s: '    """Autonomous PR reviewer — auto-merges at confidence > 0.95."""' },
      { t: "gap", s: "" },
      { t: "code", s: "    def __init__(self, model='gpt-4o'):" },
      { t: "code", s: "        self.llm = ChatModel(model, temperature=0.1)" },
      { t: "code", s: "        self.tools = [GitDiffTool(), ASTAnalyzer(), SecurityScanner()]" },
      { t: "gap", s: "" },
      { t: "code", s: "    async def review(self, pr: PullRequest) -> ReviewResult:" },
      { t: "code", s: "        diff = await self.tools[0].get_diff(pr.number)" },
      { t: "code", s: "        vuln = await self.tools[2].scan(diff)" },
      { t: "code", s: "        analysis = await self.llm.analyze(diff, vulnerabilities=vuln)" },
      { t: "code", s: "        return ReviewResult(score=analysis.confidence," },
      { t: "code", s: "                            auto_merge=analysis.confidence > 0.95)" },
      { t: "gap", s: "" },
      { t: "cmd", s: "python -m agents.code_review --pr 847 --dry-run" },
      { t: "out", s: "⚡ Reviewing PR #847 (23 files, +412 -89)...", d: 60 },
      { t: "out", s: "✓ Confidence: 0.97 → auto-merge approved", d: 100, c: "text-emerald-400" },
    ],
  },
  /* 2 ── RAG pipeline */
  {
    time: "09:30 AM", label: "RAG Pipeline Deploy", icon: "🚀",
    lines: [
      { t: "cmd", s: "kubectl apply -f k8s/rag-pipeline.yaml" },
      { t: "out", s: "deployment.apps/rag-embedder created", d: 40 },
      { t: "out", s: "deployment.apps/rag-retriever created" },
      { t: "out", s: "service/rag-gateway configured" },
      { t: "cmd", s: "curl -s localhost:8080/health | jq .status" },
      { t: "out", s: '"healthy"', d: 80, c: "text-emerald-400" },
      { t: "cmd", s: "python benchmark.py --queries 10000 --concurrent 50" },
      { t: "out", s: "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100%  10k queries", d: 200 },
      { t: "out", s: "p50=12ms  p99=38ms  accuracy=96.2%", c: "text-emerald-400" },
      { t: "cmd", s: "python ingest.py --source s3://docs-v3 --chunk 512 --overlap 64" },
      { t: "out", s: "Indexed 2,847,391 chunks → Qdrant (cosine, dim=3072)", d: 150 },
      { t: "out", s: "✓ Pipeline live", c: "text-emerald-400" },
    ],
  },
  /* 3 ── fine-tuning */
  {
    time: "11:00 AM", label: "Model Fine-Tuning", icon: "🧠",
    lines: [
      { t: "cmd", s: "accelerate launch train.py \\" },
      { t: "cmd", s: "  --model meta-llama/Llama-4-Maverick \\" },
      { t: "cmd", s: "  --lora-rank 64 --epochs 3 --lr 2e-4" },
      { t: "out", s: "[GPU 0-7] A100 80GB × 8 — bf16 mixed precision", d: 80 },
      { t: "out", s: "Epoch 1/3 ━━━━━━━━━━━━━━━━━━━━ loss=1.247", d: 180 },
      { t: "out", s: "Epoch 2/3 ━━━━━━━━━━━━━━━━━━━━ loss=0.834", d: 160 },
      { t: "out", s: "Epoch 3/3 ━━━━━━━━━━━━━━━━━━━━ loss=0.612", d: 160 },
      { t: "out", s: "✓ Saved → checkpoints/llama-ft-v4", c: "text-emerald-400" },
      { t: "out", s: "MMLU: 78.4% (+6.2)  HumanEval: 71.3% (+8.1)", c: "text-sky-400" },
      { t: "cmd", s: "python eval.py --model ./checkpoints/llama-ft-v4 --bench mt-bench" },
      { t: "out", s: "MT-Bench score: 8.74 / 10  (baseline 7.91)", d: 120, c: "text-emerald-400" },
    ],
  },
  /* 4 ── agent swarm */
  {
    time: "01:30 PM", label: "Agent Swarm Orchestrator", icon: "⚡",
    lines: [
      { t: "hdr", s: "# orchestrator/swarm.py" },
      { t: "code", s: "class AgentSwarm:" },
      { t: "code", s: '    """Parallel multi-agent executor with consensus voting."""' },
      { t: "gap", s: "" },
      { t: "code", s: "    async def execute(self, task: Task) -> Result:" },
      { t: "code", s: "        plan = await self.planner.decompose(task)" },
      { t: "code", s: "        results = await asyncio.gather(" },
      { t: "code", s: "            *[a.run(st) for a, st in zip(self.agents, plan.subtasks)]" },
      { t: "code", s: "        )" },
      { t: "code", s: "        verdict = await self.judge.evaluate(results)" },
      { t: "code", s: "        if verdict.confidence < 0.8:" },
      { t: "code", s: "            return await self.execute(task.refine(verdict))" },
      { t: "code", s: "        return verdict.best" },
      { t: "gap", s: "" },
      { t: "cmd", s: "python -m swarm --agents 12 --task 'refactor auth module'" },
      { t: "out", s: "🔄 Spawning: planner ×1  coder ×4  reviewer ×3  tester ×2  debugger ×1  deployer ×1", d: 80 },
      { t: "out", s: "⚡ Agent[coder-0] → rewriting auth/jwt.py (147 lines)", d: 40 },
      { t: "out", s: "⚡ Agent[coder-1] → rewriting auth/oauth.py (203 lines)" },
      { t: "out", s: "⚡ Agent[coder-2] → rewriting auth/rbac.py (89 lines)" },
      { t: "out", s: "⚡ Agent[coder-3] → rewriting auth/session.py (112 lines)" },
      { t: "out", s: "✓ reviewer-0 approved (confidence 0.96)", d: 60, c: "text-emerald-400" },
      { t: "out", s: "✓ 847 lines refactored, 0 regressions, merged to main", c: "text-emerald-400" },
    ],
  },
  /* 5 ── tool-use agent */
  {
    time: "03:00 PM", label: "Tool-Use Agent Build", icon: "🛠️",
    lines: [
      { t: "hdr", s: "# agents/tool_agent.py" },
      { t: "code", s: "class ToolUseAgent(ReActAgent):" },
      { t: "code", s: "    tools = [" },
      { t: "code", s: "        WebSearch(), SQLQuery(), PythonREPL()," },
      { t: "code", s: "        FileSystem(), APIClient(), Calculator()," },
      { t: "code", s: "    ]" },
      { t: "gap", s: "" },
      { t: "code", s: "    async def step(self, obs: str) -> Action:" },
      { t: "code", s: "        thought = await self.llm.think(self.history + [obs])" },
      { t: "code", s: "        tool, args = self.parse_action(thought)" },
      { t: "code", s: "        result = await self.tools[tool].execute(**args)" },
      { t: "code", s: "        self.history.append((thought, result))" },
      { t: "code", s: "        if self.is_final(result):" },
      { t: "code", s: "            return Action(type='finish', payload=result)" },
      { t: "code", s: "        return Action(type='continue', payload=result)" },
      { t: "gap", s: "" },
      { t: "cmd", s: "python -m agents.tool_agent --task 'find CVEs in requirements.txt'" },
      { t: "out", s: "→ Thought: I need to read the requirements file first", d: 50 },
      { t: "out", s: "→ Action: FileSystem.read('requirements.txt')" },
      { t: "out", s: "→ Thought: Now search for known CVEs in these packages", d: 40 },
      { t: "out", s: "→ Action: WebSearch('CVE flask 2.3.1 OR requests 2.31.0')" },
      { t: "out", s: "→ Result: Found 2 critical, 1 moderate vulnerability", d: 60 },
      { t: "out", s: "✓ Report generated → security_audit_2026-02-26.md", c: "text-emerald-400" },
    ],
  },
  /* 6 ── streaming inference */
  {
    time: "04:45 PM", label: "Streaming Inference API", icon: "📡",
    lines: [
      { t: "hdr", s: "// api/inference/stream.ts" },
      { t: "code", s: "export async function* streamInference(" },
      { t: "code", s: "  prompt: string, model: ModelConfig" },
      { t: "code", s: "): AsyncGenerator<Token> {" },
      { t: "code", s: "  const sess = await gpu.allocate(model.vram);" },
      { t: "code", s: "  for await (const tok of model.generate(prompt)) {" },
      { t: "code", s: "    metrics.track('tps', sess.tokensPerSecond);" },
      { t: "code", s: "    yield { text: tok.decode(), latency: tok.ms };" },
      { t: "code", s: "  }" },
      { t: "code", s: "  gpu.release(sess);" },
      { t: "code", s: "}" },
      { t: "gap", s: "" },
      { t: "cmd", s: "bun run build && bun run deploy:edge" },
      { t: "out", s: "✓ Build complete in 2.1s (847 modules)", d: 80 },
      { t: "out", s: "✓ Deployed to 12 edge locations", d: 60, c: "text-emerald-400" },
      { t: "cmd", s: "hey -n 5000 -c 200 https://api.misha.dev/stream" },
      { t: "out", s: "Requests/sec: 1,247.3  p99: 42ms  0 errors", d: 150, c: "text-sky-400" },
    ],
  },
  /* 7 ── data pipeline */
  {
    time: "05:30 PM", label: "Data Pipeline ETL", icon: "🔄",
    lines: [
      { t: "cmd", s: "python -m pipeline.run --source kafka --sink bigquery" },
      { t: "out", s: "Connecting to kafka://prod-cluster:9092...", d: 60 },
      { t: "out", s: "✓ Consuming from 12 partitions", d: 40, c: "text-emerald-400" },
      { t: "out", s: "Transform: dedupe → normalize → embed → validate", d: 30 },
      { t: "out", s: "Throughput: 84,291 events/sec", c: "text-sky-400" },
      { t: "cmd", s: "python -m pipeline.validate --sample 10000" },
      { t: "out", s: "Schema compliance: 100%  Null rate: 0.02%  Duplicates: 0", d: 80 },
      { t: "out", s: "✓ Pipeline healthy", c: "text-emerald-400" },
      { t: "hdr", s: "# pipeline/transforms.py" },
      { t: "code", s: "class EmbeddingTransform(BaseTransform):" },
      { t: "code", s: "    async def process(self, batch: list[Record]) -> list[Record]:" },
      { t: "code", s: "        texts = [r.content for r in batch]" },
      { t: "code", s: "        embeddings = await self.model.encode(texts, batch_size=256)" },
      { t: "code", s: "        for r, emb in zip(batch, embeddings):" },
      { t: "code", s: "            r.vector = emb.tolist()" },
      { t: "code", s: "        return batch" },
    ],
  },
  /* 8 ── sub-agent spawning */
  {
    time: "06:15 PM", label: "Sub-Agent Spawner", icon: "🌐",
    lines: [
      { t: "hdr", s: "# agents/spawner.py" },
      { t: "code", s: "class AgentSpawner:" },
      { t: "code", s: "    async def spawn(self, spec: AgentSpec) -> RunningAgent:" },
      { t: "code", s: "        container = await self.k8s.create_pod(" },
      { t: "code", s: "            image=spec.image, gpu=spec.requires_gpu," },
      { t: "code", s: "            env={'MODEL': spec.model, 'TASK': spec.task_id}" },
      { t: "code", s: "        )" },
      { t: "code", s: "        return RunningAgent(pid=container.id, ws=self.connect(container))" },
      { t: "gap", s: "" },
      { t: "cmd", s: "python -m spawner --fleet research-batch-042" },
      { t: "out", s: "Spawning sub-agent fleet (8 agents):", d: 60 },
      { t: "out", s: "  → agent-summarizer   (Llama-4-Scout)    ✓ ready", d: 30 },
      { t: "out", s: "  → agent-classifier   (BERT-large)      ✓ ready" },
      { t: "out", s: "  → agent-embedder     (E5-large-v2)     ✓ ready" },
      { t: "out", s: "  → agent-extractor    (GPT-4o-mini)     ✓ ready" },
      { t: "out", s: "  → agent-validator    (custom-ft-v3)    ✓ ready" },
      { t: "out", s: "  → agent-ranker       (ColBERT-v2)      ✓ ready" },
      { t: "out", s: "  → agent-writer       (Claude-Sonnet-4)  ✓ ready" },
      { t: "out", s: "  → agent-orchestrator (GPT-4o)          ✓ ready" },
      { t: "out", s: "Fleet online — processing 12,847 tasks in queue", d: 40, c: "text-emerald-400" },
    ],
  },
  /* 9 ── shipping */
  {
    time: "07:30 PM", label: "Ship & Monitor", icon: "🎯",
    lines: [
      { t: "cmd", s: "git add -A && git commit -m 'feat: agent swarm v2 + streaming api'" },
      { t: "out", s: "[main e7b4d08] feat: agent swarm v2 + streaming api", d: 50 },
      { t: "out", s: " 23 files changed, 1,847 insertions(+), 412 deletions(-)" },
      { t: "cmd", s: "git push origin main" },
      { t: "out", s: "remote: ✓ CI — 247/247 tests passing", d: 100 },
      { t: "out", s: "remote: ✓ Docker built (1.2GB → 340MB)", d: 60 },
      { t: "out", s: "remote: ✓ Deployed us-east-1, eu-west-1, ap-southeast-1", d: 60 },
      { t: "out", s: "remote: ✓ Health checks green on all 3 regions", c: "text-emerald-400" },
      { t: "cmd", s: "grafana-cli dashboard open prod-overview" },
      { t: "out", s: "Requests: 12.4k/min  Errors: 0.01%  p99: 34ms", d: 80, c: "text-sky-400" },
      { t: "out", s: "GPU util: 78%  Memory: 62%  Cost: $2.14/hr", c: "text-sky-400" },
      { t: "cmd", s: "echo '✨ shipped.'" },
      { t: "out", s: "✨ shipped.", d: 40, c: "text-primary" },
    ],
  },
]
